/** C1 authoring content, not a runtime verdict or a new wire contract. */
export const TEACH_FEEDBACK_BOUNDARY = "仅判断当前讲解是否接上：无未解决矛盾时接受相关的明确自述，或关键关系正确的复述；若同时出现误解/没懂/问题先澄清补讲。沉默、超时、播放结束、旧拍确认和跳过不算理解；不要求独立计算或固定UI，不记为独立掌握。";
export const MAINLINE_CONTENT = [
  {
    beat: "BT-01", resource: "RES1", title: "题设与目标",
    purpose: "Teach：帮助学生接上等腰、等角、翻折三类题设与目标线段 BE。",
    relation: "知道 AB=AC、D 在 BC 上、给定角相等和 C 翻折至 E，并能定位目标 BE",
    narration: "先看等腰、等角和翻折条件，再找到要讨论的 BE。你可以告诉我哪里已跟上、哪里还需要定位。",
    restatement: "我知道是把 C 沿 AD 翻到 E，最后看 BE。",
    misconception: "E 是随便在线段 BC 上取的点。",
    teacher: "E 是 C 关于 AD 翻折后的对应点，不是任取点。我们先对照题图认清 C、E 与折痕。",
    board: "题图保留 authored E；展示 FN-01..04，不提前构造 O。",
  },
  {
    beat: "BT-02", resource: "RES2", title: "第一组相似及用途",
    purpose: "Teach：讲清 △CAD∽△CBA 的对应关系与 AA 依据，确认学生跟得上，不要求独立证明。",
    relation: "两组对应角支持 AA；C-A-D 对应 C-B-A，相似关系用于连接已知边和待求边",
    narration: "我们把两组对应角对齐，得到第一组子母型相似。这一步用来把已知边和待求边连起来；不必先独立证明才能继续听。",
    restatement: "是两组角对应相等，所以可以用相似把已知边和 AD 连起来。",
    misconception: "懂了，相似就是所有对应边都一样长。",
    teacher: "相似要求对应边成比例，不是都相等。先对照对应顺序，再看两组三角形大小的比例。",
    board: "可讲解时展示 FN-05/FN-06 对应角和第一组相似，不等待 GT-02 算对。",
  },
  {
    beat: "BT-03", resource: "RES3", title: "比例和前置长度",
    purpose: "Teach：老师演示第一组相似比与 AD、CD、BD 的求法，确认比例和线段差已接上。",
    relation: "相似比方向统一；AD、CD 来自对应边比例，BD 是 BC 减 CD",
    narration: "我来演示相似比怎样带出 AD、CD，再用整段减去 CD 得到 BD。你只需反馈比例方向和线段差是否接上，不必提交数值。",
    restatement: "先按对应顺序求 AD、CD，再用 BC 减 CD 求 BD。",
    misconception: "BD 应该用 BC 加 CD。",
    teacher: "D 在 BC 上，BC 由 BD 和 DC 拼成。我们沿同一线段看整段与部分，再写减法。",
    board: "展示 CA:CB=AD:BA=CD:CA=2:3；AD=CD=8/3、BD=10/3，均为批准中间材料。",
  },
  {
    beat: "BT-04", resource: "RES4", title: "第二组相似与点序",
    purpose: "Teach：老师演示 O、第二组相似及四段长度的来源，确认对应关系和点序接上，不强制画布填数。",
    relation: "△DAO∽△DBA 的对应关系；先由比例得 AO、DO，再依 B-O-D-C 与 A-O-E 求 BO、OE",
    narration: "先看 O 的位置和第二组相似，再把比例计算与线段差分开讲。AO、DO、BO、OE 可由老师演示，不把画布填数当作继续听讲的门槛。",
    restatement: "AO、DO 用相似比例求，BO、OE 再根据点的顺序做减法。",
    misconception: "懂了，OE 应该是 AE 加 AO。",
    teacher: "A、O、E 的顺序决定 AE 是整段，所以 OE=AE−AO。先回到点序，再接回长度关系。",
    board: "复用 RES7 构造 O→AO/DO/BO/OE；讲解时显示 AO=16/5、DO=32/15、BO=6/5、OE=4/5；Teach 不挂 RES8 填数模板。",
  },
  {
    beat: "BT-05", resource: "RES5", title: "蝶形相似与收束",
    purpose: "Teach：讲清蝶形相似和 BE 的求法，确认学生理解比例链；最终结论只在当前 Teach 批准 Beat 的受限展示许可下演示。",
    relation: "BO:AO 与 OE:OD 同向相等且夹角相等，得到 △BOE∽△AOD，再由 BE:AD 求 BE",
    narration: "先把两组对应边比例与夹角放在一起，再接到 BE 与 AD 的比例。这里关心你是否接上推理，不要求自己算出答案后老师才讲方法。",
    restatement: "需要两边成比例和夹角相等，得到蝶形相似后再接 BE 与 AD。",
    misconception: "只要有一组对顶角就一定相似。",
    teacher: "仅有一组角相等还不够；本题还要核对夹角两侧的对应边比例。我们回看这两组比。",
    board: "FN-20..22 可作中间讲解：BO:AO=OE:OD=3:8，△BOE∽△AOD，BE:AD=3:8；FN-23 的 BE=1 可由老师演示后再确认跟上：依据 protocol/v3 的 follow_along 当前 Beat 受限教学许可，不先伪造 GT-05 studentpass；assessment 不变。",
  },
  {
    beat: "BT-06", resource: "RES6", title: "全链总结",
    purpose: "Teach：把两组子母型与蝶形连接成解题地图，接受相关自述或复述，不把总结升级为独立掌握测验。",
    relation: "第一组给前置长度，第二组接入翻折和 O 的长度，蝶形把这些长度接到目标 BE",
    narration: "我们回看整条路线。你可以说哪里已经连起来，也可以用自己的话讲一段；已有清楚反馈时不再要求重复同义确认。",
    restatement: "第一组准备长度，第二组处理翻折和 O，最后蝶形把这些关系接到 BE。",
    misconception: "前两组和最后求 BE 没有什么关系。",
    teacher: "我们沿依赖往回看：蝶形需要的两组边比来自第二组长度，第二组又用了第一组求出的 AD、BD。",
    board: "展示已讲过的三段关系图；不以最后一句懂了反填前面各拍确认，也不新增掌握结论。",
  },
] as const;
