import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {selectGivenAngleMarks,projectGivenAngles} from '../KnownGivenAngleProjection';
const plan=JSON.parse(readFileSync(join(__dirname,'../../planBuild/review/geometry-visual/candidate-v14/TP-SMV-009.v14.draft.json'),'utf8'));
const binding=plan.resource_bindings.find((b:any)=>b.binding_id==='VB-101');
const facts=[{fact_id:'FN-03',role:'given',reveals_answer:false}];
const geometry={points:['A','C','D'].map(id=>({id}))};
it('copies explicit given rays without scope lease or transitive facts',()=>{const marks=selectGivenAngleMarks([binding],facts);expect(projectGivenAngles(marks,geometry)).toEqual([{id:'given-angle:VB-101',kind:'angle-equality',source:'problem-given',angles:[{vertex:'A',rayPoints:['D','C'],sector:'minor'},{vertex:'C',rayPoints:['A','D'],sector:'minor'}]}]);expect(JSON.stringify(marks)).not.toMatch(/lease|outcome|degree|ABC/);});
it.each(['derived','goal'])('rejects %s basis',role=>expect(selectGivenAngleMarks([binding],[{...facts[0],role}])).toEqual([]));
it('rejects answer or unknown or mixed basis',()=>{expect(selectGivenAngleMarks([binding],[{...facts[0],reveals_answer:true}])).toEqual([]);expect(selectGivenAngleMarks([binding],[])).toEqual([]);expect(selectGivenAngleMarks([{...binding,basis_refs:['FN-03','FN-secret']}],facts)).toEqual([]);});
it('rejects empty basis and malformed duplicate rays',()=>{expect(selectGivenAngleMarks([{...binding,basis_refs:[]}],facts)).toEqual([]);const b=structuredClone(binding);b.relation.angles[0].ray_points=['A','C'];expect(selectGivenAngleMarks([b],facts)).toEqual([]);});
it('missing current geometry point removes whole relation',()=>{expect(projectGivenAngles(selectGivenAngleMarks([binding],facts),{points:[{id:'A'},{id:'C'}]})).toEqual([]);});
it('returned data cannot mutate source or subsequent projection',()=>{const marks=selectGivenAngleMarks([binding],facts);const result=projectGivenAngles(marks,geometry);result[0].angles[0].rayPoints[0]='X';expect(projectGivenAngles(marks,geometry)[0].angles[0].rayPoints).toEqual(['D','C']);expect(binding.relation.angles[0].ray_points).toEqual(['D','C']);});
