import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {lowerAdjacentVisualBlock} from '../BoundedVisualLowering';
import {V14_VISUAL_PRESENTER_SYSTEM_PROMPT,usesBoundedVisualLowering} from '../PresenterPrompts';
import type {PresentationDraftV2} from '../GeneratorPort';
const raw:PresentationDraftV2=JSON.parse(readFileSync(resolve('src/services/tutorOrchestration/presentationGeneration/__tests__/fixtures/v13Bt02AdjacentVisual.json'),'utf8'));
const issues=[{binding_ref:'VB-104',code:'late-visual' as const,draft_item_index:7}];
const target=new Map([[7,'VB-104']]);
const lower=(d=raw,targets=target)=>lowerAdjacentVisualBlock(d,issues,targets);
it('recorded source is immutable and pure permutation preserves every item exactly once and speech order',()=>{const before=JSON.stringify(raw);const r=lower();expect(r.sourceIndices.slice(7,10)).toEqual([8,9,7]);expect(r.moves).toHaveLength(1);expect(JSON.stringify(raw)).toBe(before);expect(r.draft.items.filter(i=>i.type==='speech')).toEqual(raw.items.filter(i=>i.type==='speech'));expect([...r.sourceIndices].sort((a,b)=>a-b)).toEqual(raw.items.map((_,i)=>i));r.draft.items[9].text='mutation';expect(JSON.stringify(raw)).toBe(before);});
it('already valid input is unchanged and normalization is idempotent, deterministic',()=>{expect(lowerAdjacentVisualBlock(raw,[],target).draft).toEqual(raw);const first=lower();expect(lower()).toEqual(first);expect(lower(first.draft).draft).toEqual(first.draft);expect(lower(first.draft).moves).toEqual([]);});
it('ambiguous structural source is never resolved from adjacent tools',()=>expect(lower(raw,new Map()).moves).toEqual([]));
it.each(['speech','board.explain','geometry.construct','geometry.clear-visual','unknown.tool'])('does not cross %s to seek later visual block',boundary=>{const d=structuredClone(raw);d.items.splice(8,0,boundary==='speech'?{type:'speech',text:'another',basis_refs:[]}:{type:'tool_intent',tool:boundary,args:{params:{group:'g'}}});expect(lower(d).moves).toEqual([]);});
it.each([1,2])('maximal continuous block with another focus/pair %s is wholly refused',pair_index=>{const d=structuredClone(raw);d.items.splice(10,0,{type:'tool_intent',tool:'geometry.emphasize',args:{binding_ref:'VB-104',params:{group:'g',pair_index,mode:'pulse'}}});expect(lower(d).moves).toEqual([]);});
it('mixed binding or group in contiguous block is refused',()=>{for(const change of ['binding','group']){const d=structuredClone(raw);if(change==='binding')d.items[8].args!.binding_ref='VB-102';else d.items[8].args!.params!.group='other';expect(lower(d).moves).toEqual([]);}});
it('prefix active group conflict cannot borrow future group',()=>{const d=structuredClone(raw);d.items[4].args!.params!.group='other';expect(lower(d).moves).toEqual([]);});
it('missing following focus is not synthesized',()=>{const d=structuredClone(raw);d.items.splice(9,1);expect(lower(d).moves).toEqual([]);});
it('whole draft with two independent movable blocks is refused instead of first-wins',()=>{const d=structuredClone(raw);d.items.splice(10,0,structuredClone(d.items[7]),structuredClone(d.items[8]),structuredClone(d.items[9]));const two=[{binding_ref:'VB-104',code:'late-visual' as const,draft_item_index:7},{binding_ref:'VB-104',code:'late-visual' as const,draft_item_index:10}];const r=lowerAdjacentVisualBlock(d,two,new Map([[7,'VB-104'],[10,'VB-104']]));expect(r.moves).toEqual([]);expect(r.sourceIndices).toEqual(d.items.map((_,i)=>i));expect(r.draft).toEqual(d);});
it('only v15 enables normalization',()=>{expect(usesBoundedVisualLowering('presenter-interleaved/v14-visual')).toBe(false);expect(usesBoundedVisualLowering('presenter-interleaved/v15-visual')).toBe(true);});
