import { describe,it,expect } from "vitest";
import { createHash } from "node:crypto";
import { visualStateSchema, visualViewSchema, geometryVisualCommandSchema, type VisualBinding, type VisualOwner, type VisualRequirement } from "../../../../../../shared/canonical/visualSchemas";
import { VisualBindingCatalog } from "../../../tutorSession/VisualBindingCatalog";
import { emptyVisualState, reduceVisual, rollbackVisualLeaseChanges, invalidateVisualOwner, type VisualActionKey } from "../../../tutorSession/WorkspaceVisualReducer";
import { projectVisualView } from "../../../tutorSession/VisualViewProjector";
import { VisualIntentCompiler } from "../VisualIntentCompiler";
import { validateVisualCoverage } from "../VisualCoverageValidator";
import { projectVisualContext } from "../VisualContextProjection";
import { visibleVisualTools } from "../VisualPresentationTools";
import { TOOL_INVOCATION_PRESENTER_SYSTEM_PROMPT, PRESENTER_SYSTEM_PROMPT } from "../PresenterPrompts";
const owner:VisualOwner={scope:{kind:"approved",protocol_id:"PR-SMV-001",beat_id:"BT-02"},scope_epoch:1,part_ref:"Q1"};
const inquiry:VisualOwner={scope:{kind:"local",inquiry_id:"IQ-test1",local_protocol_id:"LPR-test1",local_beat_id:"LBT-1",anchor:{protocol_id:"PR-SMV-001",beat_id:"BT-02"}},scope_epoch:2,part_ref:"Q1"};
const basis={binding_kind:"geometry_visual" as const,purpose:"approved relation",basis_refs:["FN-01"],allowed_scopes:[owner.scope,inquiry.scope],reveal_scope:"intermediate_result" as const,required_constructions:[],max_lifetime:"problem-part" as const};
const length:VisualBinding={...basis,binding_id:"VB-1",relation:{type:"segment-measure",segment:"AB",expression_ref:"FN-01"},allowed_forms:["length-label"]};
const similarity:VisualBinding={...basis,binding_id:"VB-2",relation:{type:"similarity",left:["A","B","C"],right:["D","E","F"],proof_angle_bindings:[]},allowed_forms:["paired-sides","triangle-outline"]};
const angle:VisualBinding={...basis,binding_id:"VB-3",relation:{type:"angle-equality",angles:[{vertex:"A",ray_points:["B","C"],sector:"minor"},{vertex:"D",ray_points:["E","F"],sector:"minor"}]},allowed_forms:["angle-arcs"]};
const points=new Map(Object.entries({A:{x:0,y:0},B:{x:2,y:0},C:{x:0,y:2},D:{x:4,y:0},E:{x:5,y:0},F:{x:4,y:1}}));
const source=(bindings=[length,similarity,angle])=>({planHash:`sha256:${"a".repeat(64)}`,bindings,approvedBasisRefs:new Set(["FN-01"]),approvedScopes:new Set(["PR-SMV-001/BT-02","IQ-test1/LPR-test1/LBT-1"]),expressions:new Map([["FN-01","AB=2"]]),pointIds:new Set(points.keys()),segments:new Map<string,readonly[string,string]>([["AB",["A","B"]]]),constructionOutputs:new Map<string,string[]>()});
const permission={completedConstructions:new Set<string>(),existingPoints:points,revealAuthorized:()=>true};
const action=(id="WSA-test-1",ordinal=0):VisualActionKey=>({session_id:"TS-test",sequence_id:"PS-0001",ordinal,action_id:id});
const compiler=(state=emptyVisualState(),own=owner,catalog=new VisualBindingCatalog(source()))=>new VisualIntentCompiler({catalog,state,owner:own,sessionId:"TS-test",sequenceId:"PS-0001",permission});
const annotate=(form="length-label",lifetime="teaching-scope",group?:string)=>({tool_id:"geometry.annotate",binding_ref:"VB-1",params:{form,lifetime,...(group?{group}:{})}});
const auth=(own=owner)=>({...permission,currentOwner:own,ownerAuthorized:()=>true});
const apply=(command:ReturnType<VisualIntentCompiler["compile"]>["command"],state=emptyVisualState(),own=owner,key=action())=>reduceVisual(state,command,new VisualBindingCatalog(source()),{...permission,owner:own,action:key});
import { compilePresentationIntents, type IntentCompilerInput } from "../IntentCompiler";
import { buildPresentationContext,DEFAULT_CONTEXT_POLICY } from "../ContextBuilder";
import { VISUAL_PRESENTER_PROMPT_VERSION } from "../PresenterPrompts";
import { VISUAL_CONTEXT_BUILDER_VERSION,VISUAL_TOOL_CATALOG_VERSION } from "../VisualPresentationTools";
import { prepareVisualInvalidation,foldVisualInvalidation } from "../../../tutorSession/WorkspaceVisualReducer";
const compiledInput=():IntentCompilerInput=>{
 const facts=new Map([["FN-01",{fact_id:"FN-01",role:"given" as const,statement:"AB=2",reveals_answer:false}]]);
 const context=buildPresentationContext({planRef:{artifact_id:"TP-SMV-009",version:"v14",content_hash:`sha256:${"a".repeat(64)}`},graphRef:{artifact_id:"RG-SMV-001",version:"v8",content_hash:`sha256:${"b".repeat(64)}`},graph:{facts,inferences:new Map()},beat:{protocol_id:"PR-SMV-001",beat_id:"BT-02",graph_fact_refs:["FN-01"],inference_refs:[],resource_ids:[]},recentInputs:[],eventCutoff:1,workspaceRevision:0,currentRevision:1,policy:DEFAULT_CONTEXT_POLICY,sessionMode:"teaching"});
 return {sessionId:"TS-8102",sequenceSerial:1,decisionId:"TD-8102-0001",scope:{kind:"approved",protocol_id:"PR-SMV-001",beat_id:"BT-02"},request:{request_id:"GR-8102-0001",attempt:1,epoch:1,input_digest:context.digest,presenter_pin:{provider:"offline",model_id:"offline",prompt_version:VISUAL_PRESENTER_PROMPT_VERSION,context_builder_version:VISUAL_CONTEXT_BUILDER_VERSION,tool_catalog_version:VISUAL_TOOL_CATALOG_VERSION}},draft:{schema:"ai_teaching_presentation_draft/v2",request_id:"GR-8102-0001",items:[{type:"tool_intent",tool:"geometry.annotate",args:{binding_ref:"VB-1",params:{form:"length-label",lifetime:"teaching-scope"}}},{type:"speech",text:"AB的批准长度是2。",basis_refs:["VB-1"]}]},context,visibleTools:[],resources:new Map(),graph:{facts,inferences:new Map()},approvedConstructions:[],revealAuthorized:()=>false};
};
import * as prompts from '../PresenterPrompts';
function input(version=prompts.VISUAL_PRESENTER_PROMPT_VERSION){
 const base=compiledInput(),catalog=new VisualBindingCatalog(source());
 const historic=apply(compiler().compile(annotate(),0,action().action_id).command).state;
 return {...base,request:{...base.request,presenter_pin:{...base.request.presenter_pin,prompt_version:version}},visual:{catalog,state:historic,owner,permission,requirements:[{scope:owner.scope,binding_ref:'VB-1',forms:['length-label' as const],required_pair_indices:[],trigger:'introduce' as const}],alreadyPresented:projectVisualView(historic,catalog,auth()),visibleTools:visibleVisualTools({bindings:[length],scope:owner.scope,sessionMode:'teaching',registeredCapabilities:new Set(['geometry.visual.upsert','geometry.visual.focus','geometry.visual.close-group']),revealAuthorized:()=>true})}};
}
const focus={type:'tool_intent' as const,tool:'geometry.emphasize',args:{binding_ref:'VB-1',params:{group:'current',mode:'steady'}}};
const close={type:'tool_intent' as const,tool:'geometry.clear-visual',args:{params:{group:'current'}}};
it('history cannot discharge v9 form; v8 remains readable',()=>{for(const v of [prompts.VISUAL_PRESENTER_PROMPT_VERSION,prompts.V8_VISUAL_PRESENTER_PROMPT_VERSION]){const c=input(v);c.draft.items=[c.draft.items[1]];if(v===prompts.VISUAL_PRESENTER_PROMPT_VERSION)expect(()=>compilePresentationIntents(c)).toThrow(/missing-form/);else expect(()=>compilePresentationIntents(c)).not.toThrow();}});
it('upsert without speech focus fails',()=>{expect(()=>compilePresentationIntents(input())).toThrow(/missing-focus/);});
it('focus keeps current information through speech without state mutation',()=>{const c=input(),before=JSON.stringify(c.visual.state);c.draft.items.splice(1,0,focus);expect(()=>compilePresentationIntents(c)).not.toThrow();expect(JSON.stringify(c.visual.state)).toBe(before);});
it('late forms cannot reuse history',()=>{const c=input();c.draft.items=[focus,c.draft.items[1],c.draft.items[0]];expect(()=>compilePresentationIntents(c)).toThrow(/late-visual/);});
it('closed focus cannot accompany speech',()=>{const c=input();c.draft.items.splice(1,0,focus,close);expect(()=>compilePresentationIntents(c)).toThrow(/missing-focus/);});
it('illegal tool wins over missing forms',()=>{const c=input();c.draft.items=[{type:'tool_intent',tool:'illegal.tool',args:{}}];try{compilePresentationIntents(c);expect.fail('must reject');}catch(e){expect(e).toMatchObject({code:'ILLEGAL_TOOL'});}});
it('unreferenced transition does not require focus',()=>{const c=input();c.draft.items[1]={type:'speech',text:'现在整理一下。',basis_refs:[]};expect(()=>compilePresentationIntents(c)).not.toThrow();});
it('v5-v8 bytes stay frozen',()=>{const names=['LEGACY_VISUAL_PRESENTER_SYSTEM_PROMPT','PREVIOUS_VISUAL_PRESENTER_SYSTEM_PROMPT','V7_VISUAL_PRESENTER_SYSTEM_PROMPT','V8_VISUAL_PRESENTER_SYSTEM_PROMPT'] as const;expect(names.map(n=>createHash('sha256').update(prompts[n]).digest('hex'))).toEqual(['fb272f62ebfaf77f14dc8bbd676f452c90347f02268a93a5c9b674ce282612e7','5c1db3333aa7813b54126c4b7dd039ff7ad7aff0ce86b535e50a1824c561e4b9','60c2a4adb2dd5aa95b508b455a1a916e54ba056e309ad8160a28b97025cbd4de','262e855cb05555c63c5a0a96e23e67504005575fe5fb39e00c2682b88306b532']);expect(prompts.VISUAL_PRESENTER_SYSTEM_PROMPT).not.toContain('真实已确认且仍可见');});
import {compilePresentationIntentsForPreflight,VisualObligationQualityError} from '../IntentCompiler';
import {structuredPresenterGenerator} from '../GeneratorPort';
import type {StructuredModelPort} from '../../../tutorIntelligence/structuredModelPort';
it('another active binding cannot accompany earlier relation speech',()=>{
 const c=compiler();const a=c.compile({tool_id:'geometry.emphasize',binding_ref:'VB-1',params:{group:'current',mode:'steady'}},0,'WSA-one');
 const b=c.compile({tool_id:'geometry.emphasize',binding_ref:'VB-3',params:{group:'current',mode:'steady'}},1,'WSA-two');
 const i=input();expect(validateVisualCoverage(i.visual.requirements,[a,b],i.visual.alreadyPresented,[{ordinal:2,binding_ref:'VB-1'}],{requireCurrentPresentation:true})).toContainEqual({binding_ref:'VB-1',code:'missing-focus'});
});
it('missing focus remains uncommitted diagnostics for preflight then typed bounded repair',()=>{const c=input(),before=JSON.stringify(c.visual.state);const r=compilePresentationIntentsForPreflight(c);expect(r.visualCoverageIssues).toContainEqual({binding_ref:'VB-1',code:'missing-focus'});expect(new VisualObligationQualityError(r.visualCoverageIssues)).toMatchObject({failureClass:'draft_invalid',retryable:true});expect(JSON.stringify(c.visual.state)).toBe(before);});
it('factory accepts v8 frozen and v9 new pins with unchanged context contract',()=>{for(const version of [prompts.V8_VISUAL_PRESENTER_PROMPT_VERSION,prompts.VISUAL_PRESENTER_PROMPT_VERSION]){const p=structuredPresenterGenerator({provider:'offline',modelId:'offline'} as StructuredModelPort,{promptVersion:version});expect(p.pin).toMatchObject({prompt_version:version,context_builder_version:VISUAL_CONTEXT_BUILDER_VERSION});}});
