/** Synthetic approval ONLY inside a disposable test root. Never qualifies as RT1 approval. */
import assert from "node:assert/strict";
import { cpSync, mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { canonicalHash, type TutorPlanV5Payload } from "../canonicalInputs";
import { importApprovedPlanV5 } from "../v5/ImportApprovedPlanV5";
import { preparePlanV7Candidate } from "../v7/PreparePlanV7Candidate";
import { publishApprovedPlanV7 } from "../v7/PublishApprovedPlanV7";
import { buildRuntimeRegistrySnapshot } from "../RuntimeRegistrySnapshot";
import { buildNavigatorPlan } from "../../tutorNavigator/NavigatorPlanV5";
const root = resolve(process.env.AI_TEACHING_CANONICAL_ROOT ?? "../../../teaching-skills-mvp/artifacts/canonical-authoring");
const loaded = importApprovedPlanV5({ canonicalRoot: root }, "TP-SMV-009");
assert.ok(loaded.ok, loaded.ok ? "" : loaded.errors.join("; "));
const source = loaded.imported;
assert.equal(source.plan.schema, "ai_teaching_tutor_plan_bundle/v5");
const bindings = JSON.parse(readFileSync(resolve("src/services/planBuild/review/s2-rt1/bindings.proposed.json"), "utf8"));
const inputs = { ...source, snapshot: buildRuntimeRegistrySnapshot() };
const prepared = preparePlanV7Candidate({ canonicalRoot: root }, "TP-SMV-009", "v12", bindings, "2026-09-07T00:00:00Z");
assert.equal(prepared.candidate.status, "Draft");
assert.equal(prepared.candidate.approval, undefined);
assert.deepEqual(prepared.candidate.resources, source.plan.resources);
assert.deepEqual(prepared.candidate.chunks, source.plan.chunks);
assert.deepEqual(prepared.candidate.resolution_profiles, source.plan.resolution_profiles);
const temp = mkdtempSync(join(tmpdir(), "SYNTHETIC-ONLY-plan-v7-"));
try {
  for (const ns of ["tutor-plan", "question-truth", "approach-set", "reviewed-solution-graph", "teaching-protocol", "tutor-policy-profile"]) cpSync(join(root, ns), join(temp, ns), { recursive: true });
  assert.equal(publishApprovedPlanV7(temp, prepared.candidate, inputs, prepared.candidate.content_hash).ok, false);
  const approved = structuredClone(prepared.candidate);
  approved.status = "Approved";
  approved.approval = { reviewer_id: "SYNTHETIC-TEST-ONLY", approved_at: "2026-09-07T00:00:00Z", review_note: "TEST ONLY. Not human approval; disposable root." };
  assert.equal(publishApprovedPlanV7(temp, approved, inputs, source.plan.content_hash).ok, false);
  const published = publishApprovedPlanV7(temp, approved, inputs, approved.content_hash);
  assert.ok(published.ok, published.ok ? "" : published.errors.join("; "));
  assert.equal(publishApprovedPlanV7(temp, approved, inputs, approved.content_hash).ok, false);
  const imported = importApprovedPlanV5({ canonicalRoot: temp }, "TP-SMV-009");
  assert.ok(imported.ok, imported.ok ? "" : imported.errors.join("; "));
  assert.equal(imported.imported.plan.schema, "ai_teaching_tutor_plan_bundle/v7");
  assert.deepEqual(imported.imported.plan.resource_bindings, bindings);
  assert.deepEqual(imported.imported.projection.resource_bindings, bindings);
  assert.doesNotThrow(() => buildNavigatorPlan(imported.imported));
  assert.notEqual(imported.imported.projection_hash, source.projection_hash);
  const file = join(temp, "tutor-plan/TP-SMV-009/v12.json");
  const registry = join(temp, "tutor-plan/TP-SMV-009/registry.yaml");
  const originalRegistry = readFileSync(registry, "utf8");
  function reject(label: string, mutate: (p: TutorPlanV5Payload) => void, reanchor = true) {
    const changed = structuredClone(approved); mutate(changed);
    changed.content_hash = canonicalHash(changed as unknown as Record<string, unknown>, "plan");
    writeFileSync(file, JSON.stringify(changed));
    writeFileSync(registry, reanchor ? originalRegistry.replaceAll(approved.content_hash, changed.content_hash) : originalRegistry);
    const result = importApprovedPlanV5({ canonicalRoot: temp }, "TP-SMV-009");
    assert.equal(result.ok, false, label);
    console.log(`PASS v7 rejects ${label}`);
  }
  reject("registry hash drift", p => { p.resource_bindings![0].purpose += " tamper"; }, false);
  reject("registry version mismatch", p => { p.version = "v99"; p.artifact_uri = "artifact://tutor-plan/TP-SMV-009@v99"; });
  reject("missing approval", p => { delete p.approval; });
  reject("Draft", p => { p.status = "Draft"; delete p.approval; });
  reject("stale graph hash", p => { p.solution_graph_ref.content_hash = "sha256:" + "0".repeat(64); });
  reject("missing gate", p => { const b = p.resource_bindings!.find(x => x.binding_kind === "board")!; if (b.binding_kind === "board") b.reveal_after_gate.gate_id = "GT-99"; });
  reject("unknown board entry", p => { const b = p.resource_bindings!.find(x => x.binding_kind === "board")!; if (b.binding_kind === "board") b.board_entry_id = "BE-99"; });
  reject("unknown construction", p => { const b = p.resource_bindings![0]; if (b.binding_kind === "geometry") b.allowed_template_ids = ["invented-output"]; });
  reject("unknown geometry target", p => { const b = p.resource_bindings![0]; if (b.binding_kind === "geometry") b.geometry_target = "invented-point"; });
  reject("unknown basis", p => { const b = p.resource_bindings![5]; if (b.binding_kind === "explanation") b.basis_refs.fact_ids.push("FN-99"); });
  reject("missing inference premise", p => { const b = p.resource_bindings![5]; if (b.binding_kind === "explanation") b.basis_refs.fact_ids.shift(); });
  reject("missing presentation resource", p => { const b = p.resource_bindings![5]; if (b.binding_kind === "explanation") b.presentation_resource = "RES99"; });
  reject("retired v6 schema", p => { (p as unknown as Record<string, unknown>).schema = "ai_teaching_tutor_plan_bundle/v6"; });
  console.log("PASS real v5 compatibility, Draft derivation, exact reviewed hash, synthetic v7 publication/import/Navigator plan and append-only guard");
} finally { rmSync(temp, { recursive: true, force: true }); }
