import {it,expect} from 'vitest';
import {join} from 'node:path';
import {importVisualReviewCandidate} from '../ImportVisualReviewCandidate';
import {realCanonicalRoot,questionOn,QUESTION_IN_BOUND} from '../../../tutorNavigator/__tests__/navigatorSupport';
import {NavigatorSessionV7} from '../../../tutorNavigator/NavigatorSessionV7';
import {FixedResponseGateProvider} from '../../../tutorNavigator/ModelGateAdjudicatorV5';
import {TutorTaskBindingResolver} from '../../../tutorOrchestration/TutorTaskBindingResolver';
import {workspaceCatalogPin} from '../../../tutorSession/WorkspacePresentationCatalogV5';
import {createPinnedVisualWorkspaceBridge} from '../../../tutorSession/VisualViewProjector';
import {visualAuthorityAt} from '../../../tutorSession/VisualBindingAuthority';
import {projectVisualContext} from '../../../tutorOrchestration/presentationGeneration/VisualContextProjection';
import {visibleVisualTools} from '../../../tutorOrchestration/presentationGeneration/VisualPresentationTools';
import {VisualIntentCompiler} from '../../../tutorOrchestration/presentationGeneration/VisualIntentCompiler';
import {reduceVisual} from '../../../tutorSession/WorkspaceVisualReducer';
it('actual Draft v14 approved Inquiry reuses only anchor bindings within current reasoning permission under its own owner',async()=>{
 const loaded=importVisualReviewCandidate({canonicalRoot:realCanonicalRoot(),candidateDirectory:join(__dirname,'../../review/geometry-visual/candidate-v14')});if(!loaded.ok)throw Error(loaded.errors.join(';'));
 const resolver=new TutorTaskBindingResolver(realCanonicalRoot(),()=>loaded),binding=resolver.resolveForStart('goldenMinhangFold2020');
 const session=NavigatorSessionV7.start({sessionId:'TS-946001',studentId:'visual-inquiry',taskId:binding.taskId,scenarioId:binding.scenarioId,sessionMode:'teaching',plan:binding.plan,imported:loaded.imported,registryProvider:resolver.v7RegistryProvider,sessionStartedPins:{workspace_catalog_pin:workspaceCatalogPin(binding.golden.catalog)},gateProvider:new FixedResponseGateProvider([questionOn('FN-03')])});
 await session.submitStudentInput({client_request_id:'open-approved',input:{kind:'utterance',channel:'mainline',text:QUESTION_IN_BOUND}});
 const authority=visualAuthorityAt(session.events,loaded.imported);
 expect(authority.currentOwner.scope).toEqual({kind:'approved',protocol_id:'PR-SMV-002',beat_id:'BT-01'});
 expect(authority.inquiryAnchor?.scope).toEqual({kind:'approved',protocol_id:'PR-SMV-001',beat_id:'BT-01'});
 const bridge=createPinnedVisualWorkspaceBridge({sessionId:session.sessionId,catalogHash:workspaceCatalogPin(binding.golden.catalog).content_hash,catalog:loaded.visual.catalog,workspaceCatalog:binding.golden.catalog,imported:loaded.imported,authorityAt:events=>visualAuthorityAt(events,loaded.imported)});
 const source=bridge.generationAt(session.events),permission=source.authorization;
 const visual=projectVisualContext({state:source.state,catalog:source.catalog,authorization:permission,requirements:source.requirements,outcomes:[],sessionId:session.sessionId,eventCutoff:session.events.at(-1)!.sequence,availableChars:16000});
 expect(visual.bindings.map(b=>b.binding_id)).toContain('VB-101');
 expect(visual.requirements).toContainEqual(expect.objectContaining({binding_ref:'VB-101',scope:authority.currentOwner.scope,trigger:'clarify-reference'}));
 expect(visual.bindings.every(b=>b.reveal_scope!=='final_result')).toBe(true);
 const tools=visibleVisualTools({bindings:visual.bindings,scope:authority.currentOwner.scope,scopeAllows:permission.scopeAllows,sessionMode:'teaching',registeredCapabilities:new Set(resolver.v10RegistryProvider(session.events[0].payload).capabilities.keys()),revealAuthorized:permission.revealAuthorized});
 expect(tools.find(t=>t.tool==='geometry.annotate')?.binding_refs).toContain('VB-101');
 const compiler=new VisualIntentCompiler({catalog:source.catalog,state:source.state,owner:authority.currentOwner,sessionId:session.sessionId,sequenceId:'PS-0001',permission});
 const compiled=compiler.compile({tool_id:'geometry.annotate',binding_ref:'VB-101',params:{form:'angle-arcs',lifetime:'teaching-scope'}},0,'WSA-946001-0001');
 const applied=reduceVisual(source.state,compiled.command,source.catalog,{...permission,owner:authority.currentOwner,action:{session_id:session.sessionId,sequence_id:'PS-0001',ordinal:0,action_id:compiled.action_id}});
 expect(applied.state.annotations[0].leases[0].owner).toEqual(authority.currentOwner);
 expect(()=>source.catalog.resolve('VB-101',{...permission,scope:authority.currentOwner.scope,lifetime:'problem-part'})).toThrow(/VB-101/);
 expect(()=>source.catalog.resolve('VB-112',{...permission,scope:authority.currentOwner.scope})).toThrow();
 expect(()=>source.catalog.resolve('VB-101',{...permission,revealAuthorized:()=>false,scope:authority.currentOwner.scope})).toThrow();
 expect(()=>source.catalog.resolve('VB-101',{...permission,scopeAllows:undefined,scope:authority.currentOwner.scope})).toThrow();
 for(const b of source.catalog.list().filter(b=>b.reveal_scope==='final_result'))expect(permission.revealAuthorized(b)).toBe(false);
 await session.submitStudentInput({client_request_id:'return-approved',input:{kind:'control',command:'return_to_mainline'}});
 const returned=visualAuthorityAt(session.events,loaded.imported);
 expect(returned.currentOwner).toEqual(authority.inquiryAnchor);
 expect(returned.inquiryAnchor).toBeUndefined();
 const after=bridge.generationAt(session.events);
 expect(after.authorization.inquiryScope).toBeUndefined();
 expect(()=>after.catalog.resolve('VB-101',{...after.authorization,scope:authority.currentOwner.scope})).toThrow();
 expect(session.assertReplayParity().equal).toBe(true);
});
