import {frozenVisualGeneration,VISUAL_CONTEXT_POLICY} from '../../../tutorOrchestration/presentationGeneration/FrozenVisualGeneration';
import type {StoredSessionEvent} from '../../../tutorSession/kernel/sessionKernelTypes';
import {buildGoldenWorkspaceCatalogV5} from '../../../tutorOrchestration/GoldenWorkspaceCatalog';
import {compilePresentationIntents,type IntentCompilerInput} from '../../../tutorOrchestration/presentationGeneration/IntentCompiler';
import {visiblePresentationTools,type PresentationResourceBinding} from '../../../tutorOrchestration/presentationGeneration/PresentationToolCatalog';
import {preflightPresentationSequence} from '../../../tutorOrchestration/presentationGeneration/SequencePreflight';
import {emptyVisualState} from '../../../tutorSession/WorkspaceVisualReducer';
import {createPinnedVisualWorkspaceBridge,projectVisualView} from '../../../tutorSession/VisualViewProjector';
import {V14_VISUAL_PRESENTER_PROMPT_VERSION} from '../../../tutorOrchestration/presentationGeneration/PresenterPrompts';
import {it,expect} from 'vitest';
import {join} from 'node:path';
import {readFileSync,mkdtempSync,cpSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {importVisualReviewCandidate} from '../ImportVisualReviewCandidate';
import {importReviewCandidate} from '../../c1/ImportReviewCandidate';
import {attachFirstTopicBaseAngleCandidate} from '../FirstTopicBaseAngleCandidate';
import {realCanonicalRoot} from '../../../tutorNavigator/__tests__/navigatorSupport';
import {buildNavigatorPlan} from '../../../tutorNavigator/NavigatorPlanV5';
import {buildPresentationContext,DEFAULT_CONTEXT_POLICY} from '../../../tutorOrchestration/presentationGeneration/ContextBuilder';
import {visibleVisualTools} from '../../../tutorOrchestration/presentationGeneration/VisualPresentationTools';
import {selectGivenAngleMarks} from '../../../tutorOrchestration/KnownGivenAngleProjection';
const directory=(v:string)=>join(__dirname,`../../review/geometry-visual/candidate-${v}`);
const load=(v='v15')=>{const r=importVisualReviewCandidate({canonicalRoot:realCanonicalRoot(),candidateDirectory:directory(v)});if(!r.ok)throw Error(r.errors.join(';'));return r;};
function source(){const r=importReviewCandidate({canonicalRoot:realCanonicalRoot(),candidateDirectory:join(directory('v15'),'base')});if(!r.ok)throw Error(r.errors.join(';'));return {plan:r.imported.plan,graphHash:r.imported.graph.content_hash,facts:new Map(r.imported.graph.facts.map(f=>[f.fact_id,f])),inferences:r.imported.graph.inferences};}
it('real v15 import preserves old bindings, board resources, graph and protocol pins',()=>{const old=load('v14'),next=load();expect(next.imported.plan.status).toBe('Draft');expect(next.imported.plan.approval).toBeUndefined();expect(next.imported.graph).toEqual(old.imported.graph);expect([...next.imported.protocols]).toEqual([...old.imported.protocols]);expect(next.imported.plan.resources).toEqual(old.imported.plan.resources);expect(next.visual.catalog.list().slice(0,-1)).toEqual(old.visual.catalog.list());expect(next.visual.catalog.get('VB-120')).toMatchObject({basis_refs:['FN-01'],relation:{type:'angle-equality',angles:[{vertex:'B',ray_points:['A','C']},{vertex:'C',ray_points:['A','B']}]}});});
it('v14 reader and file remain byte stable without new relation',()=>{const file=join(directory('v14'),'TP-SMV-009.v14.draft.json'),before=readFileSync(file);expect(load('v14').imported.plan.content_hash).toBe('sha256:d69a2b1fc5f331b392d70d0ec9a57b5f770bf0e796dad6b0ddad92805c11549d');expect(()=>load('v14').visual.catalog.get('VB-120')).toThrow();load();expect(readFileSync(file)).toEqual(before);});
it.each(['graph','fact','inference','occupied'] as const)('authoring rejects %s drift',kind=>{const s=structuredClone(source());if(kind==='graph')s.graphHash='sha256:bad';if(kind==='fact')s.facts.get('FN-01')!.statement='$AB=5$';if(kind==='inference')s.inferences.find(i=>i.inference_id==='IF-01')!.derivation='unknown';if(kind==='occupied')s.plan.resource_bindings!.push({...s.plan.resource_bindings![0],binding_id:'VB-120'});expect(()=>attachFirstTopicBaseAngleCandidate(s)).toThrow();});
it('reader rejects tampered relation, evidence and unregistered version',()=>{for(const fault of ['relation','evidence','version']){const temp=mkdtempSync(join(tmpdir(),'base-angle-test-'));try{cpSync(directory('v15'),temp,{recursive:true});const file=join(temp,fault==='relation'?'TP-SMV-009.v15.draft.json':fault==='evidence'?'visual-binding-evidence.json':'visual-review-manifest.json');const d=JSON.parse(readFileSync(file,'utf8'));if(fault==='relation')d.resource_bindings.find((b:any)=>b.binding_id==='VB-120').relation.angles[0].vertex='A';else if(fault==='evidence')d.at(-1).derived_relation='wrong';else d.plan_version='v16';writeFileSync(file,JSON.stringify(d));expect(importVisualReviewCandidate({canonicalRoot:realCanonicalRoot(),candidateDirectory:temp}).ok).toBe(false);}finally{rmSync(temp,{recursive:true,force:true});}}});
it('BT01 context preserves default budget and FN01 permission without IF01 expansion',()=>{const {imported,visual}=load(),p=buildNavigatorPlan(imported),protocol=imported.protocols.get('PR-SMV-001')!,beat=protocol.beats.find(b=>b.beat_id==='BT-01')!;const context=buildPresentationContext({planRef:p.tutor_plan_ref,graphRef:p.solution_graph_ref,graph:{facts:new Map(imported.graph.facts.map(f=>[f.fact_id,f])),inferences:new Map(imported.graph.inferences.map(i=>[i.inference_id,i]))},beat:{protocol_id:protocol.protocol_id,beat_id:beat.beat_id,graph_fact_refs:beat.solution_refs.fact_ids,inference_refs:beat.solution_refs.inference_ids,resource_ids:beat.resource_ids??[]},recentInputs:[],eventCutoff:2,workspaceRevision:0,currentRevision:2,policy:DEFAULT_CONTEXT_POLICY,sessionMode:'teaching',resourceContent:id=>imported.plan.resources.find(r=>r.resource_id===id)?.content});expect(context.context.selected_fact_ids).toContain('FN-01');expect(context.context.selected_inference_ids).not.toContain('IF-01');const refs=new Set([...context.context.selected_fact_ids,...context.context.selected_inference_ids]);const tools=visibleVisualTools({bindings:visual.catalog.list(),scope:{kind:'approved',protocol_id:protocol.protocol_id,beat_id:beat.beat_id},sessionMode:'teaching',registeredCapabilities:new Set(['geometry.visual.upsert','geometry.visual.focus','geometry.visual.close-group']),revealAuthorized:b=>b.basis_refs.every(r=>refs.has(r))});expect(tools.find(t=>t.tool==='geometry.annotate')!.binding_refs).toContain('VB-120');expect(tools.find(t=>t.tool==='geometry.annotate')!.binding_refs).not.toContain('VB-102');
 const scope={kind:'approved' as const,protocol_id:protocol.protocol_id,beat_id:beat.beat_id},owner={scope,scope_epoch:1,part_ref:'1'},workspace=buildGoldenWorkspaceCatalogV5(imported).catalog;
 const graph={facts:new Map(imported.graph.facts.map(f=>[f.fact_id,f])),inferences:new Map(imported.graph.inferences.map(i=>[i.inference_id,i]))};
 const ordinary=visiblePresentationTools({registeredCapabilities:new Set(['solution_board.explain_fragment','board.explain']),bindings:imported.plan.resource_bindings as PresentationResourceBinding[],sessionMode:'teaching',scopeAllows:b=>b.binding_kind==='explanation'&&(beat.resource_ids??[]).includes(b.presentation_resource)});
 const items:IntentCompilerInput['draft']['items']=[];
 for(const id of ['VB-101','VB-120'])items.push({type:'tool_intent',tool:'geometry.annotate',args:{binding_ref:id,params:{form:'angle-arcs',lifetime:'teaching-scope',group:'g'}}},{type:'tool_intent',tool:'geometry.emphasize',args:{binding_ref:id,params:{group:'g',mode:'pulse'}}},{type:'speech',text:id==='VB-120'?'AB=AC，所以两个底角相等。':'观察题设给定的两个相等角。',basis_refs:[id]});
 items.push({type:'tool_intent',tool:'board.explain',args:{binding_ref:'VB-06',params:{note_kind:'approved_math_note'}}},{type:'tool_intent',tool:'geometry.clear-visual',args:{params:{group:'g'}}});
 const permission={completedConstructions:new Set<string>(),existingPoints:new Map(workspace.baseGeometry!.points.map(p=>[p.id,{x:p.x,y:p.y}])),revealAuthorized:(b:{basis_refs:string[]})=>b.basis_refs.every(r=>refs.has(r))};
 const v={catalog:visual.catalog,state:emptyVisualState(),owner,permission,constructionWorld:{revision:0,geometry:workspace.baseGeometry},requirements:visual.requirements.filter(r=>r.scope.kind==='approved'&&r.scope.beat_id==='BT-01'),alreadyPresented:projectVisualView(emptyVisualState(),visual.catalog,{...permission,currentOwner:owner,ownerAuthorized:()=>true}),visibleTools:tools};
 expect(v.alreadyPresented.annotations).toEqual([]);
 const compiled=compilePresentationIntents({sessionId:'TS-9501',sequenceSerial:1,decisionId:'TD-9501-0001',scope,request:{request_id:'GR-9501-0001',attempt:1,epoch:1,input_digest:context.digest,presenter_pin:{provider:'offline',model_id:'offline',prompt_version:V14_VISUAL_PRESENTER_PROMPT_VERSION,context_builder_version:'presentation-context-builder/v2-visual',tool_catalog_version:'presentation-tool-catalog/v2-visual'}},draft:{schema:'ai_teaching_presentation_draft/v2',request_id:'GR-9501-0001',items},context,visibleTools:ordinary,resources:new Map(imported.plan.resources.map(r=>[r.resource_id,r])),graph,approvedConstructions:[],revealAuthorized:()=>false,visual:v});
 const bridge=createPinnedVisualWorkspaceBridge({sessionId:'TS-9501',catalogHash:`sha256:${'a'.repeat(64)}`,catalog:visual.catalog,workspaceCatalog:workspace,imported,authorityAt:()=>({currentOwner:owner,activeOwners:[owner]})});
 const history:StoredSessionEvent[]=[{session_id:'TS-9501',schema:'ai_teaching_tutor_session_event/v10',sequence:1,state_revision:1,occurred_at:'2026-09-08T00:00:00Z',idempotency_key:'base-angle-start',event_type:'session_started',payload:{initial_cursor:{protocol_id:'PR-SMV-001',beat_id:'BT-01'},task_id:workspace.taskId,protocol_refs:[{artifact_id:'PR-SMV-001'}],session_mode:'teaching'}},{session_id:'TS-9501',schema:'ai_teaching_tutor_session_event/v10',sequence:2,state_revision:2,occurred_at:'2026-09-08T00:00:00Z',idempotency_key:'base-angle-decision',event_type:'policy_decision_made',payload:{decision_id:'TD-9501-0001',protocol_id:'PR-SMV-001',beat_id:'BT-01',decision_kind:'execute_beat'}}];
 const fold=bridge.foldAt(history).workspace;
 expect(preflightPresentationSequence({fold,catalog:workspace,plan:compiled,visual:v}).ok).toBe(true);
 expect(compiled.actions.length).toBeLessThanOrEqual(32);
 expect(fold.state.revision).toBe(0);
 // Production reservation/retry projection, not a hand-appended visual payload.
 const freeze=()=>frozenVisualGeneration({base:context,events:history,hooks:bridge,sessionId:'TS-9501',capabilities:new Set(['geometry.visual.upsert','geometry.visual.focus','geometry.visual.close-group'])});
 const frozen=freeze();
 expect(DEFAULT_CONTEXT_POLICY.max_total_chars).toBe(4000);
 expect(VISUAL_CONTEXT_POLICY.max_total_chars).toBe(16000);
 expect(frozen.context.budget.approx_chars).toBe(context.budget.approx_chars+frozen.context.visual.chars);
 expect(frozen.context.budget.approx_chars).toBeLessThanOrEqual(VISUAL_CONTEXT_POLICY.max_total_chars);
 expect(frozen.context.visual.requirements.map(r=>r.binding_ref).sort()).toEqual(['VB-101','VB-120']);
 expect(frozen.context.visual.bindings.map(b=>b.binding_id).sort()).toEqual(['VB-101','VB-120']);
 expect(frozen.context.context.selected_inference_ids).not.toContain('IF-01');
 expect(frozen.visual.visibleTools.find(t=>t.tool==='geometry.annotate')!.binding_refs).toContain('VB-120');
 expect(frozen.source.authorization.revealAuthorized(visual.catalog.get('VB-120'))).toBe(true);
 expect(frozen.source.authorization.revealAuthorized(visual.catalog.get('VB-102'))).toBe(false);
 expect(frozen.context.visual.already_presented.annotations).toEqual([]);
 expect(frozen.context.digest).not.toEqual(context.digest);
 expect(freeze().context).toEqual(frozen.context);
 const future={...history[1],sequence:3,state_revision:3,idempotency_key:'future-uncommitted-to-cutoff',payload:{...history[1].payload,beat_id:'BT-02'}};
 expect(frozenVisualGeneration({base:context,events:[...history,future],hooks:bridge,sessionId:'TS-9501',capabilities:new Set(['geometry.visual.upsert','geometry.visual.focus','geometry.visual.close-group'])}).context.digest).toBe(frozen.context.digest);
 expect(()=>frozenVisualGeneration({base:{...context,budget:{...context.budget,approx_chars:16000}},events:history,hooks:bridge,sessionId:'TS-9501',capabilities:new Set()})).toThrow(/remaining shared budget/);

});
it('derived base angles are not problem-given before presentation',()=>{const {imported,visual}=load();expect(selectGivenAngleMarks(visual.catalog.list(),imported.graph.facts).map(m=>m.id)).toEqual(['given-angle:VB-101']);});
